= PPFCs Part 2: Crowdsourcing


=== A scalable contribution model
For our purposes, contribution has two distinct forms:

 . The administration of classes and sections and
 . The creation/modification of educational resources/assets

==== Scaling the administration of classes and sections
Recent xMOOCs have proved that only few administrative contributions can go a long way. CS50x was administered only once in the latter half of 2012 and saw over 10,000 students complete the class [3]. Peer grading and discussion forums have helped removed administration as a bottleneck for essay grading and office-hours style questions.

Unfortunately, this model precludes more frequent, smaller classes. PPFCs are designed such that students interact with only the course material and their peers. A group of peers may begin on a PPFC independent of administrative availability, thus eliminating the need to scale the administration of classes.

==== The creation/modification of educational resources/assets
Resources/assets that can be contributed to in a scaled manner include (for example):

 * Course goals & syllabus
 * Review questions with an intelligent tutoring system (ITS)
 * Slide presentations and lecture transcripts With 
 * Quizzes/Exams

Resources/assets that cannot be contributed to in a scaled manner include (for example):

 * Video/Audio recordings

PPFCs will supplement contributed resources with student engagement. In a flipped classroom, at least passing familiarity with (not necessarily comprehension of) the class topic is assumed. This model will allow a student (or students) in the class to present the lecture presentations and transcripts. Correct class sizes, well written, correctly flipped lectures and an intuitive interface will be key to making student lead discussions successful.

=== A scalable consumption model
Course discovery is a key component to scaling the student base of a learning platform. Unlike OERs, PPFCs align with traditional course numbers and a centralized course catalog. xMOOCs have shown such course catalogs to be highly effective.

=== Quality of experience
Online offerings are unlikely to ever reach the quality of an on-campus, top-tier university program. However, an interactive, synchronous class would provide a more enriching experience than current online programs can offer. While there are advantages to self-paced courses, following a schedule improves self-certification rates in online classes.

