= Pure-peer flipped classrooms: Creating courses that anyone can edit

Crowdsourced platforms like Wikipedia, GitHub and Uber have profoundly improved various information and service verticals. Why have online learning platforms not driven similar improvements in education?

I'll be using this blog to explore this question and propose a propose a platform that I belive can bring crowdsoucing to education.

== Current OERs and MOOCs are missing something
Crowdsourced projects like Wikipedia successfully leverage the crowd for contribution and provide high quality content and/or services at scale. These projects necessarily excel at three things:

 . A scalable contribution model
 . A scalable consumption model and
 . Content/service quality comparable to traditional non-crowdsourced options
 
 
Existing online learning platform fail to provide one or more of thsese. MOOCs are written in a top-down manner that precludes open contribution while OERs often lack enough course structure to be widely accessable to students. Pure-peer flipped classrooms/courses (PPFCs) are a new way to ofer structed OERs that attempt to realize the same soft of success other crowdsourced platforms have had.

== PPFC overview

A 'flipped' classroom 

== A scalable contribution model
For our purposes, contribution has two distinct forms:

 . The administration of classes and sections and
 . The creation/modification of educational resources/assets

=== Scaling the administration of classes and sections
Recent xMOOCs have proved that only few administrative contributions can go a long way. CS50x was administered only once in the latter half of 2012 and saw over 10,000 students complete the class. Unfortunately, this model precludes more frequent, smaller classes.
PPFCs are designed such that students interact with only the course material and their peers. A group of peers may begin on a PPFC independent of administrative availability, thus eliminating the need to scale the administration of classes.

=== The creation/modification of educational resources/assets
Resources/assets that can be contributed to in a scaled manner include (for example):

 * Course goals & syllabus
 * Review questions with an intelligent tutoring system (ITS)
 * Slide presentations and lecture transcripts
 * Quizzes/Exams

Resources/assets that cannot be contributed to in a scaled manner include (for example):

 * Video/Audio recordings

PPFCs will supplement contributed resources with student engagement. In a flipped classroom, at least passing familiarity with (not necessarily comprehension of) the class topic is assumed. This model will allow a student (or students) in the class to present the lecture presentations and transcripts. Correct class sizes, well written, correctly flipped lectures and an intuitive interface will be key to making student lead discussions successful.

== A scalable consumption model
Through peer grading, discussion forms and more, existing OERs and MOOCs have made significant advances that have allowed them to effectively scale student enrollment.

=== References

[1] Creating Educational Resources at Scale http://mitros.org/p/papers/pmitros-icalt14.pdf