= Pure-peer flipped classrooms: Creating courses that anyone can edit

Crowdsourced platforms like Wikipedia, GitHub and Uber have profoundly improved various information and service verticals. Why have online learning platforms not driven similar improvements in education?

This post is first in a series that will explore this question and propose a propose a platform that I belive can bring crowdsoucing to education.

== Online learning is missing something
Successful crowdsourced platforms leverage the crowd for contribution and provide high quality content and/or services at scale. More explicity, they have:

 . A scalable contribution model
 . A scalable consumption model and
 . Content/service quality comparable to traditional non-crowdsourced options
 
Existing online learning platforms fail to provide one or more of these. Massive open online courses (MOOCs - like edx, Coursera, etc) are written in a top-down manner that precludes open contribution. Open educational resources (OERs - like MIT's OpenCourseWare) often lack enough course structure to be widely accessable to students [1].

I propose pure-peer flipped classrooms (PPFCs) as an answer to what online learning is currently missing.

== PPFC overview
A 'flipped' classroom moves lectures and other content-only material outside of the classroom and uses class time to explore content in greater depth or work on more traditional homework problems. This model removes the teacher as the central focus [2].

A 'pure peer' flipped classroom is an online class that entirely removes the instructor from the in-class experience. Students watch lectrues and read course material before attending an online class together. In class, an automated system presents a brief material review followed by questions and discussion topics that the students work through as a group. Realtime peer feedback combined with an intelligent tutoring system removes the need for instructor mediation. By letting a group of students work through a class session together, PPFCs recover the interactive experience that current online courses lack.

Running 'pure peer' clases like this will require innovative technology and high-quality content. So why bother? Because PPFCs have all three nessesary components of a succesful crowdsourced platform. PPFCs enable crowdsourced education and courses that anyone can edit.

== A scalable contribution model
For our purposes, contribution has two distinct forms:

 . The administration of classes and sections and
 . The creation/modification of educational resources/assets

=== Scaling the administration of classes and sections
Recent xMOOCs have proved that only few administrative contributions can go a long way. CS50x was administered only once in the latter half of 2012 and saw over 10,000 students complete the class [3]. Peer grading and discussion forms have helped removed adminitration as a bottleneck for essay grading and office-hours style questions.

Unfortunately, this model precludes more frequent, smaller classes. PPFCs are designed such that students interact with only the course material and their peers. A group of peers may begin on a PPFC independent of administrative availability, thus eliminating the need to scale the administration of classes.

=== The creation/modification of educational resources/assets
Resources/assets that can be contributed to in a scaled manner include (for example):

 * Course goals & syllabus
 * Review questions with an intelligent tutoring system (ITS)
 * Slide presentations and lecture transcripts With 
 * Quizzes/Exams

Resources/assets that cannot be contributed to in a scaled manner include (for example):

 * Video/Audio recordings

PPFCs will supplement contributed resources with student engagement. In a flipped classroom, at least passing familiarity with (not necessarily comprehension of) the class topic is assumed. This model will allow a student (or students) in the class to present the lecture presentations and transcripts. Correct class sizes, well written, correctly flipped lectures and an intuitive interface will be key to making student lead discussions successful.

== A scalable consumption model
Course discovery is a key component to scaling the student base of a learning platform. Unlike OERs, PPFCs align with traditional course numbers and a centralized course catalog. xMOOCs have shown such course catalogs to be highly effetive.

== Quality of experience
Online offerings are unlikely to ever reach the quality of an on-campus, top-teir university program. However, an interactive, synchronous class would provide a more enriching experience than current online programs can offer. While there are advatages to self-paced courses, following a schedule improves self-certification rates in online classes.


=== References

[1] Creating Educational Resources at Scale http://mitros.org/p/papers/pmitros-icalt14.pdf
[2] Flipped classroom https://en.wikipedia.org/wiki/Flipped_classroom
[3] This was CS50x https://blog.cs50.net/
[4] Active learning https://en.wikipedia.org/wiki/Active_learning